"use client"

import { Download, Printer, Send, FileText, CheckCircle2, Clock, AlertCircle } from "lucide-react"

export default function PoInvoicePage() {
  const lineItems = [
    { id: 1, item: "Ergonomic chair", qty: 25, price: 3500, total: 87500 },
    { id: 2, title: "Tech Core LTD", qty: 10, price: 8200, total: 82000 }
  ]

  const subtotal = 169500
  const gst = 15255 // 9%
  const grandTotal = 200010

  return (
    <div className="p-8 space-y-8 animate-fade-in min-h-full bg-[#0a0a1a]">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-start justify-between gap-6 animate-slide-up" style={{ animationDelay: "0ms" }}>
        <div>
          <h1 className="text-3xl font-bold text-white tracking-tight flex items-center gap-3">
            <FileText className="w-8 h-8 text-violet-500" />
            Purchase Order & Invoice
          </h1>
          <p className="text-white/40 mt-2 text-sm flex items-center gap-2">
            PO-2024-autogenerated after approval
            <span className="px-2 py-0.5 bg-amber-500/20 text-amber-400 text-[10px] uppercase font-bold rounded-full border border-amber-500/20">
              Pending Payment
            </span>
          </p>
        </div>
        
        <div className="flex flex-wrap items-center gap-3">
          <button className="flex items-center gap-2 px-4 py-2.5 bg-white/5 hover:bg-white/10 border border-white/10 text-white rounded-xl text-sm font-semibold transition-all">
            <Download className="w-4 h-4" /> Download PDF
          </button>
          <button className="flex items-center gap-2 px-4 py-2.5 bg-white/5 hover:bg-white/10 border border-white/10 text-white rounded-xl text-sm font-semibold transition-all">
            <Printer className="w-4 h-4" /> Print
          </button>
          <button className="flex items-center gap-2 px-4 py-2.5 bg-violet-600 hover:bg-violet-500 text-white rounded-xl text-sm font-semibold shadow-[0_0_15px_rgba(139,92,246,0.3)] transition-all">
            <Send className="w-4 h-4" /> Send Invoice
          </button>
        </div>
      </div>

      {/* Info Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 animate-slide-up" style={{ animationDelay: "100ms" }}>
        
        <div className="bg-[#0d0d20] border border-white/10 rounded-2xl p-6 shadow-xl">
          <h3 className="text-xs font-semibold text-white/40 uppercase tracking-wider mb-4 border-b border-white/10 pb-2">Bill To</h3>
          <div className="space-y-1">
            <p className="text-white/90 font-medium">Your Organization Name</p>
            <p className="text-white/60 text-sm">123 business park, ahmedabad</p>
            <p className="text-white/60 text-sm font-mono mt-2">GSTIN: 24AAACG1234D1Z5</p>
          </div>
        </div>

        <div className="bg-[#0d0d20] border border-white/10 rounded-2xl p-6 shadow-xl">
          <h3 className="text-xs font-semibold text-white/40 uppercase tracking-wider mb-4 border-b border-white/10 pb-2">Vendor</h3>
          <div className="space-y-1">
            <p className="text-white/90 font-medium">Infra supplies pvt ltd</p>
            <p className="text-white/60 text-sm">456, industrial estate, surat</p>
            <p className="text-white/60 text-sm font-mono mt-2">GSTIN: 24BBBBF9876E1Z4</p>
          </div>
        </div>

      </div>

      {/* Dates & Numbers */}
      <div className="bg-white/5 border border-white/10 rounded-2xl p-6 grid grid-cols-2 md:grid-cols-4 gap-6 animate-slide-up" style={{ animationDelay: "150ms" }}>
        <div>
          <p className="text-xs text-white/40 uppercase tracking-wider mb-1">PO Number</p>
          <p className="text-sm font-medium text-white/90 font-mono">PO-2025-0068</p>
        </div>
        <div>
          <p className="text-xs text-white/40 uppercase tracking-wider mb-1">Invoice Date</p>
          <p className="text-sm font-medium text-white/90">22 May 2025</p>
        </div>
        <div>
          <p className="text-xs text-white/40 uppercase tracking-wider mb-1">PO Date</p>
          <p className="text-sm font-medium text-white/90">21 May 2025</p>
        </div>
        <div>
          <p className="text-xs text-white/40 uppercase tracking-wider mb-1">Due Date</p>
          <p className="text-sm font-bold text-rose-400">21 June 2025</p>
        </div>
      </div>

      {/* Line Items Table */}
      <div className="bg-[#0d0d20] border border-white/10 rounded-2xl shadow-xl overflow-hidden animate-slide-up" style={{ animationDelay: "200ms" }}>
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr>
                <th className="p-4 bg-white/[0.02] border-b border-white/10 text-xs font-semibold text-white/40 uppercase tracking-wider">Item</th>
                <th className="p-4 bg-white/[0.02] border-b border-white/10 text-xs font-semibold text-white/40 uppercase tracking-wider text-right">Qty</th>
                <th className="p-4 bg-white/[0.02] border-b border-white/10 text-xs font-semibold text-white/40 uppercase tracking-wider text-right">Unit Price</th>
                <th className="p-4 bg-white/[0.02] border-b border-white/10 text-xs font-semibold text-white/40 uppercase tracking-wider text-right">Total</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {lineItems.map(item => (
                <tr key={item.id}>
                  <td className="p-4 text-white/80 font-medium text-sm">{item.item || item.title}</td>
                  <td className="p-4 text-white/60 text-sm text-right">{item.qty}</td>
                  <td className="p-4 text-white/60 text-sm text-right">₹{item.price.toLocaleString()}</td>
                  <td className="p-4 text-white/90 font-medium text-sm text-right">₹{item.total.toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr>
                <td colSpan={2} className="p-4 border-t border-white/10"></td>
                <td className="p-4 border-t border-white/10 text-white/40 text-sm text-right">Subtotal</td>
                <td className="p-4 border-t border-white/10 text-white/90 font-medium text-sm text-right">₹{subtotal.toLocaleString()}</td>
              </tr>
              <tr>
                <td colSpan={2} className="p-4"></td>
                <td className="p-4 text-white/40 text-sm text-right">CGST (9%)</td>
                <td className="p-4 text-white/90 font-medium text-sm text-right">₹{gst.toLocaleString()}</td>
              </tr>
              <tr>
                <td colSpan={2} className="p-4 border-b border-white/10"></td>
                <td className="p-4 border-b border-white/10 text-white/40 text-sm text-right">SGST (9%)</td>
                <td className="p-4 border-b border-white/10 text-white/90 font-medium text-sm text-right">₹{gst.toLocaleString()}</td>
              </tr>
              <tr className="bg-white/[0.02]">
                <td colSpan={2} className="p-6"></td>
                <td className="p-6 text-white/60 font-semibold uppercase tracking-wider text-sm text-right">Grand Total</td>
                <td className="p-6 text-emerald-400 font-bold text-xl text-right">₹{grandTotal.toLocaleString()}</td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>

      {/* Action Footer */}
      <div className="flex justify-end pt-4 animate-slide-up" style={{ animationDelay: "300ms" }}>
        <button className="text-sm text-violet-400 hover:text-violet-300 font-medium transition-colors flex items-center gap-1">
          Mark as Paid <CheckCircle2 className="w-4 h-4" />
        </button>
      </div>

    </div>
  )
}