// app/po-invoice/page.tsx
'use client';

import React, { useState } from 'react';
import {
  FileText,
  Building2,
  CreditCard,
  Package,
  Calendar,
  Hash,
  MapPin,
  Phone,
  User,
  AlertCircle,
  ChevronRight,
  Save,
  Printer,
  Send,
  DollarSign,
  ShoppingCart,
  Truck,
} from 'lucide-react';

// Type definitions
interface LineItem {
  id: string;
  item: string;
  quantity: number;
  unitPrice: number;
  total: number;
}

interface Vendor {
  name: string;
  phone: string;
  partNumber: string;
  skNumber: string;
  address: string;
  identification: string;
}

interface PurchaseOrder {
  poNumber: string;
  date: string;
  status: 'draft' | 'issued' | 'approved' | 'paid';
}

interface Invoice {
  invoiceNumber: string;
  date: string;
  dueDate: string;
  status: 'pending' | 'paid' | 'overdue';
}

// Mock data
const mockVendor: Vendor = {
  name: 'ABC Electronics Supply',
  phone: '(555) 123-4567',
  partNumber: 'ELEC-2024-001',
  skNumber: 'SK-98765432',
  address: '123 Supply Chain Blvd, Industrial City, IC 90210',
  identification: 'VAT ID: US-123456789',
};

const mockPurchaseOrder: PurchaseOrder = {
  poNumber: 'PO-2024-0087',
  date: '2024-03-15',
  status: 'approved',
};

const mockInvoice: Invoice = {
  invoiceNumber: 'INV-2024-0042',
  date: '2024-03-20',
  dueDate: '2024-04-19',
  status: 'pending',
};

// Main PO & Invoice Page Component
export default function PoInvoicePage() {
  const [lineItems, setLineItems] = useState<LineItem[]>([
    {
      id: '1',
      item: 'Industrial Power Supply Unit',
      quantity: 5,
      unitPrice: 249.99,
      total: 1249.95,
    },
    {
      id: '2',
      item: 'Precision Control Module',
      quantity: 3,
      unitPrice: 599.99,
      total: 1799.97,
    },
  ]);

  const [notes, setNotes] = useState<string>(
    'All items subject to quality inspection.\nDelivery within 14 business days.\nWarranty: 24 months standard.'
  );

  // Calculate totals
  const subtotal = lineItems.reduce((sum, item) => sum + item.total, 0);
  const taxRate = 0.08; // 8% tax
  const taxAmount = subtotal * taxRate;
  const total = subtotal + taxAmount;

  // Update line item
  const updateLineItem = (id: string, field: keyof LineItem, value: string | number) => {
    setLineItems((prev) =>
      prev.map((item) => {
        if (item.id === id) {
          const updated = { ...item, [field]: value };
          // Recalculate total if quantity or unitPrice changes
          if (field === 'quantity' || field === 'unitPrice') {
            updated.total = updated.quantity * updated.unitPrice;
          }
          return updated;
        }
        return item;
      })
    );
  };

  // Add new line item
  const addLineItem = () => {
    const newId = (Math.max(0, ...lineItems.map((item) => parseInt(item.id))) + 1).toString();
    setLineItems([
      ...lineItems,
      {
        id: newId,
        item: 'New Item',
        quantity: 1,
        unitPrice: 0,
        total: 0,
      },
    ]);
  };

  // Remove line item
  const removeLineItem = (id: string) => {
    setLineItems(lineItems.filter((item) => item.id !== id));
  };

  // Format currency
  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 2,
    }).format(amount);
  };

  // Format date
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100">
      <div className="max-w-7xl mx-auto p-6">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center justify-between">
            <div>
              <div className="flex items-center gap-3 mb-2">
                <div className="w-10 h-10 bg-blue-600 rounded-xl flex items-center justify-center shadow-lg">
                  <span className="text-white font-bold text-xl">V</span>
                </div>
                <h1 className="text-2xl font-bold text-gray-800">Vendor Bridge</h1>
              </div>
              <h2 className="text-3xl font-bold text-gray-900 mt-2">Purchase Order & Invoice</h2>
              <p className="text-gray-500 mt-1 text-sm">
                PO-2024-autogenerated after approval
              </p>
            </div>
            <div className="flex gap-3">
              <button className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 transition-colors">
                <Printer className="w-4 h-4" />
                Print
              </button>
              <button className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors shadow-sm">
                <Send className="w-4 h-4" />
                Send to Vendor
              </button>
              <button className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors shadow-sm">
                <Save className="w-4 h-4" />
                Save
              </button>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Left Column - Vendor and Document Info */}
          <div className="lg:col-span-1 space-y-6">
            {/* Vendor Card */}
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
              <div className="px-5 py-4 bg-gradient-to-r from-blue-50 to-white border-b border-gray-200">
                <div className="flex items-center gap-2">
                  <Building2 className="w-5 h-5 text-blue-600" />
                  <h3 className="font-semibold text-gray-800">Vendor Information</h3>
                </div>
              </div>
              <div className="p-5 space-y-3">
                <div className="flex items-start gap-3">
                  <User className="w-4 h-4 text-gray-400 mt-0.5" />
                  <div>
                    <p className="text-sm font-medium text-gray-900">{mockVendor.name}</p>
                    <p className="text-xs text-gray-500">{mockVendor.partNumber}</p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <Phone className="w-4 h-4 text-gray-400" />
                  <p className="text-sm text-gray-700">{mockVendor.phone}</p>
                </div>
                <div className="flex items-center gap-3">
                  <Hash className="w-4 h-4 text-gray-400" />
                  <p className="text-sm text-gray-700">SKU: {mockVendor.skNumber}</p>
                </div>
                <div className="flex items-start gap-3">
                  <MapPin className="w-4 h-4 text-gray-400 mt-0.5" />
                  <p className="text-sm text-gray-700">{mockVendor.address}</p>
                </div>
                <div className="flex items-center gap-3">
                  <CreditCard className="w-4 h-4 text-gray-400" />
                  <p className="text-sm text-gray-700">{mockVendor.identification}</p>
                </div>
              </div>
            </div>

            {/* Purchase Order Card */}
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
              <div className="px-5 py-4 bg-gradient-to-r from-green-50 to-white border-b border-gray-200">
                <div className="flex items-center gap-2">
                  <ShoppingCart className="w-5 h-5 text-green-600" />
                  <h3 className="font-semibold text-gray-800">Purchase Order</h3>
                </div>
              </div>
              <div className="p-5 space-y-3">
                <div className="flex justify-between items-center">
                  <span className="text-sm text-gray-500">PO Number:</span>
                  <span className="text-sm font-medium text-gray-900">{mockPurchaseOrder.poNumber}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-gray-500">Date:</span>
                  <span className="text-sm text-gray-700">{formatDate(mockPurchaseOrder.date)}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-gray-500">Status:</span>
                  <span className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-700">
                    <CheckCircle className="w-3 h-3" />
                    {mockPurchaseOrder.status}
                  </span>
                </div>
              </div>
            </div>

            {/* Invoice Card */}
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
              <div className="px-5 py-4 bg-gradient-to-r from-purple-50 to-white border-b border-gray-200">
                <div className="flex items-center gap-2">
                  <FileText className="w-5 h-5 text-purple-600" />
                  <h3 className="font-semibold text-gray-800">Invoice</h3>
                </div>
              </div>
              <div className="p-5 space-y-3">
                <div className="flex justify-between items-center">
                  <span className="text-sm text-gray-500">Invoice #:</span>
                  <span className="text-sm font-medium text-gray-900">{mockInvoice.invoiceNumber}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-gray-500">Date:</span>
                  <span className="text-sm text-gray-700">{formatDate(mockInvoice.date)}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-gray-500">Due Date:</span>
                  <span className="text-sm text-gray-700">{formatDate(mockInvoice.dueDate)}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-gray-500">Status:</span>
                  <span className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-xs font-medium bg-yellow-100 text-yellow-700">
                    <Clock className="w-3 h-3" />
                    {mockInvoice.status}
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Right Column - Line Items Table */}
          <div className="lg:col-span-2 space-y-6">
            {/* Line Items Table */}
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
              <div className="px-6 py-4 bg-gradient-to-r from-gray-50 to-white border-b border-gray-200">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Package className="w-5 h-5 text-gray-600" />
                    <h3 className="font-semibold text-gray-800">Line Items</h3>
                  </div>
                  <button
                    onClick={addLineItem}
                    className="text-sm text-blue-600 hover:text-blue-700 font-medium flex items-center gap-1"
                  >
                    + Add Item
                  </button>
                </div>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Item
                      </th>
                      <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider w-24">
                        Qty
                      </th>
                      <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider w-32">
                        Unit Price
                      </th>
                      <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider w-32">
                        Total
                      </th>
                      <th className="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider w-16">
                        Actions
                      </th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-200">
                    {lineItems.map((item) => (
                      <tr key={item.id} className="hover:bg-gray-50 transition-colors">
                        <td className="px-6 py-3">
                          <input
                            type="text"
                            value={item.item}
                            onChange={(e) => updateLineItem(item.id, 'item', e.target.value)}
                            className="w-full text-sm text-gray-900 bg-transparent border-0 focus:ring-0 focus:outline-none focus:border-b-2 focus:border-blue-500"
                          />
                        </td>
                        <td className="px-6 py-3">
                          <input
                            type="number"
                            value={item.quantity}
                            onChange={(e) => updateLineItem(item.id, 'quantity', parseInt(e.target.value) || 0)}
                            className="w-20 text-right text-sm text-gray-900 bg-transparent border-0 focus:ring-0 focus:outline-none focus:border-b-2 focus:border-blue-500"
                          />
                        </td>
                        <td className="px-6 py-3">
                          <input
                            type="number"
                            step="0.01"
                            value={item.unitPrice}
                            onChange={(e) => updateLineItem(item.id, 'unitPrice', parseFloat(e.target.value) || 0)}
                            className="w-28 text-right text-sm text-gray-900 bg-transparent border-0 focus:ring-0 focus:outline-none focus:border-b-2 focus:border-blue-500"
                          />
                        </td>
                        <td className="px-6 py-3 text-right text-sm font-medium text-gray-900">
                          {formatCurrency(item.total)}
                        </td>
                        <td className="px-6 py-3 text-center">
                          <button
                            onClick={() => removeLineItem(item.id)}
                            className="text-red-400 hover:text-red-600 transition-colors"
                          >
                            ×
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Totals Section */}
              <div className="border-t border-gray-200 bg-gray-50 px-6 py-4">
                <div className="flex flex-col items-end space-y-2 max-w-xs ml-auto">
                  <div className="flex justify-between w-full text-sm">
                    <span className="text-gray-600">Subtotal:</span>
                    <span className="text-gray-900">{formatCurrency(subtotal)}</span>
                  </div>
                  <div className="flex justify-between w-full text-sm">
                    <span className="text-gray-600">Tax (8%):</span>
                    <span className="text-gray-900">{formatCurrency(taxAmount)}</span>
                  </div>
                  <div className="flex justify-between w-full text-lg font-bold pt-2 border-t border-gray-300">
                    <span className="text-gray-800">Total:</span>
                    <span className="text-blue-600">{formatCurrency(total)}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Notes Section */}
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
              <div className="px-6 py-4 bg-gradient-to-r from-amber-50 to-white border-b border-gray-200">
                <div className="flex items-center gap-2">
                  <AlertCircle className="w-5 h-5 text-amber-600" />
                  <h3 className="font-semibold text-gray-800">Notes</h3>
                </div>
              </div>
              <div className="p-5">
                <textarea
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                  rows={4}
                  className="w-full text-sm text-gray-700 border border-gray-200 rounded-lg p-3 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
                  placeholder="Add any additional notes, terms, or conditions here..."
                />
              </div>
            </div>

            {/* Action Bar */}
            <div className="flex justify-end gap-3 pt-2">
              <button className="flex items-center gap-2 px-6 py-2.5 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 transition-colors">
                <Truck className="w-4 h-4" />
                Request Delivery
              </button>
              <button className="flex items-center gap-2 px-6 py-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors shadow-sm">
                <DollarSign className="w-4 h-4" />
                Process Payment
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// Helper components for icons
function CheckCircle(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  );
}

function Clock(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  );
}